apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: where-for-dinner-ui
  annotations:
    ootb.apps.tanzu.vmware.com/servicebinding-workload: "true"
    ootb.apps.tanzu.vmware.com/apidescriptor-ref: "true"
  labels:
    app.kubernetes.io/part-of: where-for-dinner-ui
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    networking.knative.dev/visibility: cluster-local
    app.kubernetes.io/component: run
    carto.run/workload-name: where-for-dinner-ui
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        conventions.carto.run/applied-conventions: |-
          spring-boot-convention/auto-configure-actuators-check
          spring-boot-convention/app-live-view-appflavour-check
          appliveview-sample/app-live-view-appflavour-check
        developer.conventions/target-containers: workload
        kubectl.kubernetes.io/last-applied-configuration: |
          {"apiVersion":"carto.run/v1alpha1","kind":"Workload","metadata":{"annotations":{},"labels":{"app.kubernetes.io/part-of":"where-for-dinner-ui","apps.tanzu.vmware.com/has-tests":"true","apps.tanzu.vmware.com/workload-type":"web","networking.knative.dev/visibility":"cluster-local"},"name":"where-for-dinner-ui","namespace":"myapps"},"spec":{"env":[{"name":"REACT_APP_PROFILE","value":"nonsecure"}],"params":[{"name":"annotations","value":{"autoscaling.knative.dev/minScale":"1"}}],"resources":{"limits":{"cpu":"2000m","memory":"3.0G"},"requests":{"cpu":"100m","memory":"250M"}},"source":{"git":{"ref":{"branch":"main"},"url":"https://github.com/vmware-tanzu/application-accelerator-samples.git"},"subPath":"where-for-dinner/where-for-dinner-ui"}}}
      labels:
        app.kubernetes.io/component: run
        app.kubernetes.io/part-of: where-for-dinner-ui
        apps.tanzu.vmware.com/has-tests: "true"
        apps.tanzu.vmware.com/workload-type: web
        carto.run/workload-name: where-for-dinner-ui
        networking.knative.dev/visibility: cluster-local
    spec:
      containers:
      - env:
        - name: REACT_APP_PROFILE
          value: nonsecure
        image: harbor.rito.tkg-vsp-lab.hyrulelab.com/tap/workloads/where-for-dinner-ui-myapps@sha256:aa4d138664bf50c03f88a819e5cc45133907a109734577feffaa418b6ae7db83
        name: workload
        resources:
          limits:
            cpu: "2"
            memory: 3G
          requests:
            cpu: 100m
            memory: 250M
        securityContext:
          runAsUser: 1000
      serviceAccountName: default

