# We need to declare intent of export for both registry and git credentials to dev namespaces
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretExport
metadata:
  name: registry-credentials
  namespace: tap-install
spec:
  toNamespaces:
    - '*'
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretExport
metadata:
  name: git-https
  namespace: tap-install
spec:
  toNamespaces:
    - '*'