apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: csharp-rest-service
  annotations:
    ootb.apps.tanzu.vmware.com/servicebinding-workload: "true"
    ootb.apps.tanzu.vmware.com/apidescriptor-ref: "true"
    kapp.k14s.io/change-rule: upsert after upserting servicebinding.io/ServiceBindings
  labels:
    apis.apps.tanzu.vmware.com/register-api: "true"
    app.kubernetes.io/part-of: csharp-rest-service
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    tanzu.app.live.view: "true"
    tanzu.app.live.view.application.actuator.port: "9090"
    tanzu.app.live.view.application.flavours: steeltoe
    tanzu.app.live.view.application.name: csharp-rest-service
    app.kubernetes.io/component: run
    carto.run/workload-name: csharp-rest-service
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        conventions.carto.run/applied-conventions: |-
          appliveview-sample/app-live-view-appflavour-check
          appliveview-sample/app-live-view-connector-steeltoe
          appliveview-sample/app-live-view-appflavours-steeltoe
          spring-boot-convention/auto-configure-actuators-check
          spring-boot-convention/app-live-view-appflavour-check
        developer.conventions/target-containers: workload
      labels:
        apis.apps.tanzu.vmware.com/register-api: "true"
        app.kubernetes.io/component: run
        app.kubernetes.io/part-of: csharp-rest-service
        apps.tanzu.vmware.com/has-tests: "true"
        apps.tanzu.vmware.com/workload-type: web
        carto.run/workload-name: csharp-rest-service
        tanzu.app.live.view: "true"
        tanzu.app.live.view.application.actuator.port: "9090"
        tanzu.app.live.view.application.flavours: steeltoe
        tanzu.app.live.view.application.name: csharp-rest-service
    spec:
      containers:
      - env:
        - name: DOTNET_CLI_TELEMETRY_OPTOUT
          value: "true"
        image: harbor.rito.tkg-vsp-lab.hyrulelab.com/tap/workloads/csharp-rest-service-myapps@sha256:7af7d03cc3be0f52820fdc74fd109c3b169d2232c5b0bbf8e7be9f55478eba79
        name: workload
        resources: {}
        securityContext:
          runAsUser: 1000
      serviceAccountName: default

