---
# We need to approve impoting git credentials to dev namespaces
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretImport
metadata:
  name: git-https
  annotations:
    tekton.dev/git-0: https://github.com
spec:
  fromNamespace: tap-install