---
tap_install:
  values:
    profile: full
    shared:
      ingress_domain: tap.akkala.tkg-vsp-lab.hyrulelab.com
      ingress_issuer: lets-encrypt-cluster-issuer
      image_registry:
        project_path: "harbor.korok.tkg-vsp-lab.hyrulelab.com/tap"
    ceip_policy_disclosed: true # Installation fails if this not set to `true`
    buildservice:
      kp_default_repository: "harbor.korok.tkg-vsp-lab.hyrulelab.com/tap/build-service"
      # exclude_dependencies: true
    supply_chain: testing_scanning
    ootb_supply_chain_testing_scanning:
      gitops:
        server_address: https://github.com/
        repository_owner: jaimegag
        repository_name: tap-gitops
        branch: main
        user_name: supplychain
        user_email: supplychain
        commit_message: supplychain@cluster.local
        ssh_secret: git-secret
        commit_strategy: direct
    tap_gui:
      service_type: ClusterIP
      metadataStoreAutoconfiguration: true
      # tls:
      #   secretName: contour-tls-delegation-cert-tls
      #   namespace: tanzu-system-ingress
      app_config:
        app:
          baseUrl: https://tap-gui.tap.akkala.tkg-vsp-lab.hyrulelab.com
        catalog:
          locations:
            - type: url
              target: https://github.com/jaimegag/tap-zone/blob/main/tap-gui/blank/catalog-info.yaml
        backend:
          baseUrl: https://tap-gui.tap.akkala.tkg-vsp-lab.hyrulelab.com
          cors:
            origin: https://tap-gui.tap.akkala.tkg-vsp-lab.hyrulelab.com
          reading:
            allow:
              - host: "where-for-dinner-default.tap.akkala.tkg-vsp-lab.hyrulelab.com"
#        proxy:
#          /metadata-store:
#            target: https://metadata-store-app.metadata-store:8443/api/v1
#            changeOrigin: true
#            secure: false
#            headers:
#              Authorization: "Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjJieGR6TTNIUlRiUHNTSko0ZndVWjhKYkhpOXdhM2N3b0c5ZWpNQVd3WWMifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJtZXRhZGF0YS1zdG9yZSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJtZXRhZGF0YS1zdG9yZS1yZWFkLXdyaXRlLWNsaWVudCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50Lm5hbWUiOiJtZXRhZGF0YS1zdG9yZS1yZWFkLXdyaXRlLWNsaWVudCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6ImFkYTZiZTdmLWI5OGMtNDIyNS05YzY1LTJjMzMzMTk5M2E5YSIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDptZXRhZGF0YS1zdG9yZTptZXRhZGF0YS1zdG9yZS1yZWFkLXdyaXRlLWNsaWVudCJ9.TIwa8QMtCHAL58LnkKQc7wChjNGN0j30HDTlBgiGHQMY9JotMZL6un1dLuzPzzC5sMtekeTTvTmTt68ll6QISyLIL_OIpPzhEYFKn6I_EcA7q7AD9b-qeyR_gyGaNgDZD_lMGC-7cUF6HOFgnZx6vpbM_7-BfEfU1tXi4rkTyxa0nW_tYwRAANEgncqNjZH4kZirROZK4zwsSTjXF3Ec5QA5c2YSmkSO85zFZuDOmkQzAmwNgX9kgyfr9VFltxi1U7rpgs7Ol2v-CZS13eZeO3YVW8g7FL1bPXv5LZjmhFTihbXQxaV-lEK-FWZoOjI-0GArsiaWmg08sGGZEfTLng"
#              X-Custom-Source: project-star
        kubernetes:
          clusterLocatorMethods:
            - type: 'config'
              clusters:
                - url: https://${KUBERNETES_SERVICE_HOST}:${KUBERNETES_SERVICE_PORT}
                  name: host
                  authProvider: serviceAccount
                  serviceAccountToken: ${KUBERNETES_SERVICE_ACCOUNT_TOKEN}
                  skipTLSVerify: true
                  skipMetricsLookup: false
                  # techdocs:
                  #   builder: 'external'
                  #   publisher:
                  #     type: 'awsS3'
                  #     awsS3:
                  #       bucketName: BUCKET-NAME
                  #       credentials:
                  #         accessKeyId: AWS-READONLY-ACCESS-KEY-ID
                  #         secretAccessKey: AWS-READONLY-SECRET-ACCESS-KEY
                  #       region: AWS-REGION
                  #       s3ForcePathStyle: false
    scanning:
      metadataStore:
        url: "" # disable the now deprecated embedded integration. Metadata Store integration was moved out from the controller and into the grype/snyk scanners integration
    metadata_store:
      ns_for_export_app_cert: "*"
      app_service_type: ClusterIP # (optional) Defaults to LoadBalancer. Change to NodePort for distributions that don't support LoadBalancer
    grype:
      namespace: "default" # (optional) Defaults to default namespace.
      targetImagePullSecret: "registry-credentials"
    contour:
      envoy:
        service:
          type: LoadBalancer
    # cnrs:
    #   domain_name: tap.akkala.tkg-vsp-lab.hyrulelab.com
    #   domain_template: "{{.Name}}.{{.Namespace}}.{{.Domain}}" # Hyphenated to leverage a single wildcard FQDN and cert for all things (GUI and apps)
    #   default_tls_secret: tanzu-system-ingress/contour-tls-delegation-cert-tls
    appliveview:
      ingressEnabled: "true"
    appliveview_connector:
      backend:
        sslDisabled: "true"
    accelerator:
      ingress:
        include: "true"
    package_overlays:
      - name: cnrs
        secrets:
          - name: cnrs-network-config-overlay
    policy:
      tuf_enabled: false # By default, TUF initialization and keyless verification are deactivated.
    namespace_provisioner:
      controller: false
      gitops_install:
        ref: origin/main
        subPath: clusters/akkala/cluster-config/namespace-provisioner/namespaces
        url: https://github.com/jaimegag/tap-gitops.git
    #excluded_packages:
