---
tap_install:
  values:
    profile: full

    shared:
      ingress_domain: tap.zora.tkg-vsp-lab.hyrulelab.com
      ingress_issuer: ""
      image_registry:
        project_path: harbor.rito.tkg-vsp-lab.hyrulelab.com/tap # Image registry project path (e.g. myregistry.azurecr.io/tap/tap-images)
        username: admin # Registry username
      kubernetes_version: 1.25.7 # Kubernetes version (e.g. 1.25.9)

    ceip_policy_disclosed: true

    # These packages will be deprecated in future versions of TAP, so we will exclude them to free up space on the cluster
    excluded_packages:
      - learningcenter.tanzu.vmware.com
      - workshops.learningcenter.tanzu.vmware.com
      - eventing.tanzu.vmware.com

    tap_gui:
      service_type: ClusterIP
      tls:
        namespace: contour-tls
        secretName: tls
      ingressEnabled: "true"
      app_config:
        auth:
          allowGuestAccess: true
          environment: development
    
    cnrs:
      default_tls_secret: contour-tls/tls
      domain_template: "{{.Name}}-{{.Namespace}}.{{.Domain}}" # this is a go-template

    namespace_provisioner:
      controller: false
      sync_period: 30s
      # configure a repo that defines which namespaces should exist
      # for simplicity, it's the same one we have been using
      gitops_install:
        ref: origin/main
        subPath: clusters/workshop/cluster-config/namespace-provisioner/namespaces
        url: https://github.com/jaimegag/tap-gitops.git
        secretRef:
          name: sync-git
          namespace: tanzu-sync
          create_export: true
