---
tap_install:
  values:
    profile: full

    shared:
      ingress_domain: tap.zora.tkg-vsp-lab.hyrulelab.com
      ingress_issuer: ""
      image_registry:
        project_path: harbor.rito.tkg-vsp-lab.hyrulelab.com/tap # Image registry project path (e.g. myregistry.azurecr.io/tap/tap-images)
        username: admin # Registry username
      kubernetes_version: 1.25.7 # Kubernetes version (e.g. 1.25.9)

    ceip_policy_disclosed: true

    # These packages will be deprecated in future versions of TAP, so we will exclude them to free up space on the cluster
    excluded_packages:
      - learningcenter.tanzu.vmware.com
      - workshops.learningcenter.tanzu.vmware.com
      - eventing.tanzu.vmware.com

    tap_gui:
      service_type: ClusterIP
      ingressEnabled: "true"
      app_config:
        auth:
          allowGuestAccess: true
          environment: development
