---
tap_install:
  values:
    profile: full

    shared:
      ingress_domain: tap.zora.tkg-vsp-lab.hyrulelab.com
      ingress_issuer: ""
      image_registry:
        project_path: harbor.rito.tkg-vsp-lab.hyrulelab.com/tap # Image registry project path (e.g. myregistry.azurecr.io/tap/tap-images)
        username: admin # Registry username
      kubernetes_version: 1.25.7 # Kubernetes version (e.g. 1.25.9)

    ceip_policy_disclosed: true

    supply_chain: testing_scanning
    ootb_supply_chain_testing_scanning:
      gitops:
        ssh_secret: git-https
        branch: main
        commit_message: "Update from TAP Supply Chain Choreographer"
        server_address: https://github.com/
        repository_owner: jaimegag
        repository_name: tap-gitops

    metadata_store:
      app_service_type: ClusterIP
      ns_for_export_app_cert: "*"

    scanning:
      metadataStore:
        url: ""

    grype:
      targetImagePullSecret: registry-credentials

    # These packages will be deprecated in future versions of TAP, so we will exclude them to free up space on the cluster
    excluded_packages:
      - learningcenter.tanzu.vmware.com
      - workshops.learningcenter.tanzu.vmware.com
      - eventing.tanzu.vmware.com

    tap_gui:
      service_type: ClusterIP
      tls:
        namespace: contour-tls
        secretName: tls
      ingressEnabled: "true"
      app_config:
        auth:
          allowGuestAccess: true
          environment: development
        catalog:
          locations:
            - type: url
              target: https://github.com/Tanzu-Solutions-Engineering/tanzu-java-web-app/blob/main/catalog/catalog-info.yaml
        integrations:
          github:
            - host: github.com
      metadataStoreAutoconfiguration: true
      kubernetes:
        clusterLocatorMethods:
          - type: 'config'
            clusters:
              - url: https://${KUBERNETES_SERVICE_HOST}:${KUBERNETES_SERVICE_PORT}
                name: host
                authProvider: serviceAccount
                serviceAccountToken: ${KUBERNETES_SERVICE_ACCOUNT_TOKEN}
                skipTLSVerify: true
                skipMetricsLookup: false

    
    cnrs:
      default_tls_secret: contour-tls/tls
      domain_template: "{{.Name}}-{{.Namespace}}.{{.Domain}}" # this is a go-template

    namespace_provisioner:
      controller: false
      sync_period: 30s
      # configure a repo that defines which namespaces should exist
      # for simplicity, it's the same one we have been using
      gitops_install:
        ref: origin/main
        subPath: clusters/workshop/cluster-config/namespace-provisioner/namespaces
        url: https://github.com/jaimegag/tap-gitops.git
        secretRef:
          name: sync-git
          namespace: tanzu-sync
          create_export: true
      additional_sources:
        # additional sources points to the resources we want to fill those namespaces with
        - git:
            url: https://github.com/jaimegag/tap-gitops.git
            ref: origin/main
            subPath: clusters/workshop/cluster-config/namespace-provisioner/namespace-resources
            secretRef:
              name: git-https # this is the new credential
              namespace: tap-install
      default_parameters:
        supply_chain_service_account:
          secrets:
            - git-https
    local_source_proxy:
      repository: harbor.rito.tkg-vsp-lab.hyrulelab.com/tap/tap-source-proxy
      push_secret:
        name: lsp-push-credentials
        namespace: tap-install
        create_export: true
